// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byvbwykreyegfbtvhlzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5dmJ3eWtyZXllZ2ZidHZobHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMjk5MjksImV4cCI6MjA1NzYwNTkyOX0.WXpeeeVYE3UR-EaPH4JaR1NSPdCM-2CUpBq34EYUj50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);